### ISSUE TITLE
More themes (VS code, Firefox, Vim, Dunst, etc.)

### ISSUE THREAD

**Issue by bsikar** [leetApe/BSPWM-Final-Rice#1]
Hey I love your theme!

I was wondering if you have themes for the following:

1. VS Code, I see that you have it in your screen shot, I would love to get the colorscheme you used for that (is it an extension)?
2. Firefox, Maybe you have a clean firefox theme?
3. Vim, I mainly would love whatever colorscheme you have. Maybe you have a VIM colorscheme?
4. Dunst! I see you use Dunst, but the default Dunst is awful, do you have a theme for that?

**Comment by leetApe** [comment]
Thank you!

The vscode theme I use is everblush which you can find [here](https://github.com/Everblush/vscode).
I currently don't have firefox theme and I'm still working on my vim config.
The dunst config are now added to the repo.

**Comment by bsikar** [comment]
Thank you!! :)))
