### ISSUE TITLE
No Border for Alacritty

### ISSUE THREAD

**Issue by bsikar** [leetApe/BSPWM-Final-Rice#2]
I see in your rice screenshot there is a border, but mine doesnt have one, any ideas?
![image](https://user-images.githubusercontent.com/65072072/176516683-b14c9112-da66-405c-9666-609fab9ccbbe.png)

**Comment by leetApe** [comment]
I apologize. I forgot to add the script for double borders, it's now added to the repo inside the bin folder.

**Comment by bsikar** [comment]
Thank you :)!!
